### ISSUE TITLE
Update Release Notes Guide per feedback

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-documentation-planning#14]
- Fix link style in Credits section and mention to copy and paste template in raw and/or comment them out so they show up
- Need to confirm that template is adequately covered by the MIT license or if a CC license should also be applied.
- Need to choose between New and Noteworthy or Highlights or What's New
- Need to choose between Additional Features and Changes or Minor Features and Changes or Other Features and Changes

Once this issue is complete, spawn this issue: Need links to examples once the release notes for 0.1.4 are completed.

**Comment by mojavelinux** [comment]
Marking as obsolete since this repository is being archived.
