### ISSUE TITLE
Add issue, commit, code logistics, and release details to infrastructure goals doc

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-documentation-planning#26]
Edit and add content to [Infrastructure Goals and Planning](https://github.com/asciidoctor/asciidoctor-documentation/blob/master/infrastructure-goals-planning.adoc), including:
- Release branches workflow (@mojavelinux, I know we discussed a modification to the standard OSS process - and my mind has lost it...)
- Testing criteria, documentation testing, and test automation details
- Issue and commit wording to facilitate changelog generation and documentation
- Documentation automation considerations I forgot -> Arg! I forgot to mention creating a docs branch for each release 
- Release engineering considerations I forgot

This issue is related to Issue #7

**Comment by mojavelinux** [comment]
Marking as obsolete since this repository is being archived.
