### ISSUE TITLE
Create Changelog directory and docs changelog

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-documentation-planning#4]
During its first incarnation the docs changelog may fill in as both its own changelog as well as the core's changelog.

However, at some point, each repository will create its own changelog and the docs changelog will resolve to solely its own record of changes.

The Changelog directory may or may not be the permanent home of all of the compiled changelogs.

TODO: I think I saw mention that GitHub can automatically generate a changelog from the issues. If so, a new issue researching this feature and its capabilities/limitations should be spawned.

**Comment by mojavelinux** [comment]
Now that the documentation has been split, the AsciiDoc docs have their on CHANGELOG file and the Asciidoctor docs share the CHANGELOG with the project. So this can now be closed.
