### ISSUE TITLE
Setup automated system/build connecting Docs repo with code repos

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-documentation-planning#7]
Setup an automated system/build connecting the Asciidoctor organization's core, integration, extension, and implementation repositories to the asciidoctor-documentation repo.

. The repos should communicate when new example code, content, etc. is available (or has been built)
. The Docs repo should be able to grab the flagged content, distribute it to all the files it is used in, and build the updated documentation so it can be distributed to various channels (currently only the website).

Initially, only Asciidoctor core and the Java Integration repo may implement this system as we work out the way to automate this process.

TODO:
- [ ] what file structure does each repo need to setup
- [ ] how will the docs be versioned (tag?)
- [ ] how will versions be preserved for support releases and archived for EOL
- [ ] how will the docs be built
- [ ] how will code be 'flagged' for inclusion
- [ ] are the repos calling the docs repo when they have new content or is the docs repo calling the other repos to check for new content?
- [ ] how will the docs be tested (build passes)
- [ ] map the content relationships between the repos' docs and the tutorials

The above tasks will probably need to be broken out into individual issues.
Once documentation is building in the Docs repo, a similar system will need to be created for the website.

Background: https://github.com/asciidoctor/asciidoctor/issues/541

**Comment by mojavelinux** [comment]
Although we haven't quite achieved all that is proposed here, Antora takes a long way. And I think the continued evolution of Antora and the docs build process will address these interrelationship. But let's revisit it with a new issue when that time comes.
